package com.eggtart.jetpackcomposeyds.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import com.eggtart.jetpackcomposeyds.ui.theme.foundation.*

data class YdsColors(
    val bgNormal: Color = BgNormal,
    val bgElevated: Color = BgElevated,
    val bgRecomment: Color = BgRecomment,
    val bgSelected: Color = BgSelected,
    val bgPressed: Color = BgPressed,
    val bgNormalReversed: Color = BgNormalReversed,
    val bgElevatedReversed: Color = BgElevatedReversed,
    val textPrimary: Color = TextPrimary,
    val textSecondary: Color = TextSecondary,
    val textTertiary: Color = TextTertiary,
    val textDisabled: Color = TextDisabled,
    val textReversed: Color = TextReversed,
    val textPointed: Color = TextPointed,
    val textWarned: Color = TextWarned,
    val dimNormal: Color = DimNormal,
    val dimThick: Color = DimThick,
    val dimThickReversed: Color = DimThickReversed,
    val borderThin: Color = BorderThin,
    val borderNormal: Color = BorderNormal,
    val borderThick: Color = BorderThick,
    val buttonNormal: Color = ButtonNormal,
    val buttonNormalPressed: Color = ButtonNormalPressed,
    val buttonBG: Color = ButtonBG,
    val buttonEmojiBG: Color = ButtonEmojiBG,
    val buttonReversed: Color = ButtonReversed,
    val buttonDisabled: Color = ButtonDisabled,
    val buttonDisabledBG: Color = ButtonDisabledBG,
    val buttonPoint: Color = ButtonPoint,
    val buttonPointPressed: Color = ButtonPointPressed,
    val buttonPointBG: Color = ButtonPointBG,
    val buttonWarned: Color = ButtonWarned,
    val buttonWarnedPressed: Color = ButtonWarnedPressed,
    val buttonWarnedBG: Color = ButtonWarnedBG,
    val bottomBarNormal: Color = BottomBarNormal,
    val bottomBarSelected: Color = BottomBarSelected,
    val inputFieldNormal: Color = InputFieldNormal,
    val inputFieldElevated: Color = InputFieldElevated,
    val toastBG: Color = ToastBG,
    val pressed: Color = Pressed,
    val shadowThin: Color = ShadowThin,
    val shadowNormal: Color = ShadowNormal,
    val monoItemPrimary: Color = MonoItemPrimary,
    val monoItemBG: Color = MonoItemBG,
    val monoItemText: Color = MonoItemText,
    val greenItemPrimary: Color = GreenItemPrimary,
    val greenItemBG: Color = GreenItemBG,
    val greenItemText: Color = GreenItemText,
    val emeraldItemPrimary: Color = EmeraldItemPrimary,
    val emeraldItemBG: Color = EmeraldItemBG,
    val emeraldItemText: Color = EmeraldItemText,
    val aquaItemPrimary: Color = AquaItemPrimary,
    val aquaItemBG: Color = AquaItemBG,
    val aquaItemText: Color = AquaItemText,
    val blueItemPrimary: Color = BlueItemPrimary,
    val blueItemBG: Color = BlueItemBG,
    val blueItemText: Color = BlueItemText,
    val indigoItemPrimary: Color = IndigoItemPrimary,
    val indigoItemBG: Color = IndigoItemBG,
    val indigoItemText: Color = IndigoItemText,
    val violetItemPrimary: Color = VioletItemPrimary,
    val violetItemBG: Color = VioletItemBG,
    val violetItemText: Color = VioletItemText,
    val purpleItemPrimary: Color = PurpleItemPrimary,
    val purpleItemBG: Color = PurpleItemBG,
    val purpleItemText: Color = PurpleItemText,
    val pinkItemPrimary: Color = PinkItemPrimary,
    val pinkItemBG: Color = PinkItemBG,
    val pinkItemText: Color = PinkItemText,
)

internal val LocalColors = staticCompositionLocalOf { YdsColors() }
